name: FlutterApp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.9.0
  # flutter_dotenv is used to load runtime ENV from .env (included below in assets).
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # .env is bundled for local/CI runs; production can swap via flavors as needed.
    - .env
    - assets/
